openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: {{varsEnv["base_url"]}}
    description: Optional server description, e.g. Main (production) server
tags:
  {% for folder in folders%}
  - name: {{folder["name"]}}
    description: Secured Admin-only calls
  {% endfor %}
paths:
  {% for folder in folders%}
  {% for route in folder["routes"] %}
  {{ route['url'].replace('{{ base_url  }}', '') }}:
  {% for method in route["methods"]%}
    {{ method["method"].lower() }}:
      tags:
        - {{folder["name"]}}
      summary: Returns a list of users.
      {% if method["description"] %}
      description: {{method["description"]}}
      {% else %}
      description: Optional extended description in CommonMark or HTML.
      {% endif %}
      {% if method["sampleRequest"] %}
      requestBody:
        required: true
        content:
          {{method["contentType"]}}:
            schema:
              {% if method["sampleRequest"] is mapping %}
              type: object
              {% endif %}
              properties:
              {% for key in method["sampleRequest"] %}
                {{key}}:
                  {% if method["sampleRequest"][key] is string %}
                  type: string
                  {% elif method["sampleRequest"][key] is number%}
                  type: integer
                  {% endif %}
              {% endfor %}
      {% endif %}
      responses:
        '200':  
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  {% endfor %}
  {% endfor %}
  {% endfor %}



